version: '3.0'
services:
  server:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxl-job-admin
    restart: always
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://25.30.15.85:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=chengxun --xxl.job.accessToken=chengxun"
    volumes:
      - ./data:/data/applogs
    ports:
      - 8888:8080