version: "3"
services:
  torna:
    image: swaggerapi/swagger-ui:v4.15.0
    container_name: swagger-ui
    restart: always
    environment:
      - SWAGGER_JSON_URL=http://25.30.15.6:8080/cube/api-docs
      - DEFAULT_MODEL_RENDERING=model
      - DEFAULT_MODELS_EXPAND_DEPTH=-1
      - DEFAULT_MODEL_EXPAND_DEPTH=2
      - DOC_EXPANSION=none
    networks:
      - devops
    ports:
      - 80:8080
networks:
  devops:
    external: true