version: "3.9"
services:
  reposilite:
    image: dzikoysk/reposilite:3.0.2
    container_name: reposilite
    ports:
      - 8088:8080
    environment:
      - JAVA_OPTS=-Xmx128M
      - REPOSILITE_OPTS=--port 8080
    volumes:
      - ./data:/app/data
    restart: always
