version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:5.14.0
    container_name: 'verdaccio'
    privileged: true
    restart: always
    environment:
      - VERDACCIO_PORT=4873
      - DEBUG=verdaccio:*
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
