version: "3"
services:
  torna:
    image: tanghc2020/torna:1.16.0
    container_name: torna
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_SCHEMA=torna
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=chengxun
    networks:
      - devops
    ports:
      - 7700:7700
networks:
  devops:
    external: true