version: "3.9"
services:
  verdaccio:
    image: verdaccio/verdaccio:5.26.3
    container_name: verdaccio
    privileged: true
    restart: always
    ports:
      - 4873:4873
    environment:
      - VERDACCIO_PORT=4873
      - DEBUG=verdaccio:*
    volumes:
      - './verdaccio/conf:/verdaccio/conf'
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --max_allowed_packet=128M
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=chengxun
    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis:6
    container_name: redis
    restart: always
    command: --requirepass redis@123
    ports:
      - 6379:6379
      